apiVersion: v1
kind: Service
metadata:
  name: intel-gpu-exporter
  labels:
    app: intel-gpu-exporter
spec:
  selector:
    app: intel-gpu-exporter
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
