apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intel-gpu-exporter
  labels:
    app: intel-gpu-exporter
spec:
  selector:
    matchLabels:
      app: intel-gpu-exporter
  namespaceSelector:
    matchNames:
      - intel-device-plugins
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
