apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stage-hitohub.yaml
  - prod-hitohub.yaml
  - ark-survival-ascended.yaml
  - ark-discord-bot.yaml
  - even-g2-lab.yaml
  - codex-workspace.yaml
  - hermes-agent.yaml
  - local-llm.yaml
  - stable-diffusion.yaml
  - palserver.yaml
  - palserver-2.yaml
