apiVersion: v1
kind: Service
metadata:
  name: minecraft-bluemap
  namespace: minecraft
spec:
  type: ClusterIP
  selector:
    app: minecraft-server
  ports:
  - name: http
    protocol: TCP
    port: 8100
    targetPort: bluemap
