apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-even-g2-lab-cloudflared
  namespace: even-g2-lab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: even-g2-lab-cloudflared-secret
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: even-g2-lab-tunnel-token
        metadataPolicy: None
