apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-hub-credentials
  namespace: ark-survival-ascended
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: docker-hub-regcred
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: /lolice/docker-hub/username
  - secretKey: password
    remoteRef:
      key: /lolice/docker-hub/password