apiVersion: v1
kind: Service
metadata:
  name: ark-server-service
  namespace: ark-survival-ascended
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.29
  selector:
    app: ark-server
  ports:
  - name: game-port
    protocol: UDP
    port: 7777
    targetPort: game-port # DeploymentのcontainerPort名に合わせる
  - name: query-port
    protocol: UDP
    port: 27015
    targetPort: query-port # DeploymentのcontainerPort名に合わせる
  - name: rcon-port
    protocol: TCP
    port: 27020
    targetPort: rcon-port # DeploymentのcontainerPort名に合わせる
