apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: grafana-alerting
        secret.reloader.stakater.com/reload: grafana-discord-webhooks
    spec:
      containers:
        - name: grafana
          env:
            - name: GRAFANA_DISCORD_WEBHOOK_BOXLAB_ALERT
              valueFrom:
                secretKeyRef:
                  name: grafana-discord-webhooks
                  key: boxlab-alert-webhook-url
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/alerting
              name: grafana-alerting
              readOnly: true
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
