apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = JST

    [database] 
    type = sqlite3

    [server]
    domain = grafana.b0xp.io
    root_url = https://grafana.b0xp.io/
