apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s
  namespace: argocd
spec:
  destination:
    namespace: k8s
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: argoproj/k8s
      repoURL: https://github.com/boxp/lolice
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
