apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-stable-diffusion-cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: stable-diffusion-cloudflared-secret
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: stable-diffusion-tunnel-token
        metadataPolicy: None

