apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-workload-priority
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoproj/gpu-workload-priority
    repoURL: https://github.com/boxp/lolice
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
