apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  destination:
    namespace: reloader
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      targetRevision: v1.0.78
      chart: stakater/reloader
      helm:
        valueFiles:
          - values.yaml
    - path: argoproj/reloader
      repoURL: https://github.com/boxp/lolice
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
