apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  destination:
    namespace: reloader
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      targetRevision: 1.0.79
      chart: reloader
      helm:
        valueFiles:
          - $lolice/values.yaml
    - path: argoproj/reloader
      repoURL: https://github.com/boxp/lolice
      targetRevision: main
      ref: lolice
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
