apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - storageclass.yaml
  - pvc.yaml
  - configmap.yaml
  - kubeconfig.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
