apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tidb-operator
  namespace: argocd
spec:
  destination:
    namespace: tidb-admin
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/boxp/lolice
      targetRevision: main
      ref: lolice
    - repoURL: https://charts.pingcap.org
      targetRevision: 1.6.0
      chart: tidb-operator
      helm:
        valueFiles:
          - $lolice/argoproj/tidb-operator/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
