apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/argoproj/argo-cd/manifests/base?ref=v3.0.5
- cloudflared-deployment.yaml
- external-secret.yaml
- base/external-secrets.yaml
- base/cloudflared-api.yaml
patchesStrategicMerge:
- overlays/argocd-redis-network-policy.yaml
- overlays/argocd-repo-server-network-policy.yaml
- overlays/argocd-server-network-policy.yaml
- overlays/argocd-cmd-params-cm.yaml
- overlays/argocd-cm.yaml
- overlays/argocd-rbac-cm.yaml
