apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ark-discord-bot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/boxp/lolice.git
    path: argoproj/ark-discord-bot
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ark-discord-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true