apiVersion: apps/v1
kind: Deployment
metadata:
  name: palserver
  namespace: palserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palserver
  template:
    metadata:
      labels:
        app: palserver
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: palserver
        image: 839695154978.dkr.ecr.ap-northeast-1.amazonaws.com/palserver:sha256:d5d1275322b020a7366874d16656e27d4d2c161c24a9f3628503b408a0b5887a
        ports:
        - containerPort: 8211
        volumeMounts:
        - name: saved-volume
          mountPath: /home/nonroot/PalServer/Pal/Saved
        resources:
          limits:
            cpu: 3500m
            memory: 24Gi
          requests: 
            cpu: 1000m
            memory: 16Gi
      volumes:
      - name: saved-volume
        persistentVolumeClaim:
          claimName: palserver-saved-claim
      affinity:
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - golyat-1
