apiVersion: apps/v1
kind: Deployment
metadata:
  name: palserver
  namespace: palserver
spec:
  replicas: 0
  selector:
    matchLabels:
      app: palserver
  template:
    metadata:
      labels:
        app: palserver
    spec:
      securityContext:
        fsGroup: 65532
      containers:
      - name: palserver
        image: 839695154978.dkr.ecr.ap-northeast-1.amazonaws.com/palserver:a1475970bfd9050f180d7d76cc280dabad937f16
        ports:
        - containerPort: 8211
          protocol: UDP
        volumeMounts:
        - name: saved-volume-v2
          mountPath: /home/nonroot/PalServer/Pal/Saved
        resources:
          limits:
            cpu: 3500m
            memory: 8Gi
          requests: 
            cpu: 1000m
            memory: 8Gi
      volumes:
      - name: saved-volume-v2
        persistentVolumeClaim:
          claimName: palserver-saved-claim-v2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - golyat-1
