apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- application.yaml
- storage-class.yaml
- persistent-volume.yaml
- persistent-volume-claim.yaml
- deployment.yaml
- service.yaml
