kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: palserver-saved-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi
