kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: palserver-saved-claim-v2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
