apiVersion: v1
kind: Service
metadata:
  name: palserver
  namespace: palserver
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.97
  selector:
    app: palserver
  ports:
  - protocol: UDP
    port: 8211
    targetPort: 8211
