alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
  mounts:
    varlog: true
controller:
  type: daemonset
  tolerations:
    - effect: NoSchedule
      operator: Exists
  nodeSelector: {}
serviceMonitor:
  enabled: true
  labels:
    app.kubernetes.io/part-of: kube-prometheus
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
