apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hitohub
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/boxp/lolice.git
      revision: HEAD
      files:
      - path: "argoproj/hitohub/overlays/**/config.json"
  template:
    metadata:
      name: '{{env}}-hitohub'
      annotations:
        argocd-image-updater.argoproj.io/image-list: frontend=839695154978.dkr.ecr.ap-northeast-1.amazonaws.com/hitohub-frontend-{{env}},backend=839695154978.dkr.ecr.ap-northeast-1.amazonaws.com/hitohub-backend-{{env}}
        argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
        argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      project: default
      source:
        repoURL: https://github.com/boxp/lolice.git
        targetRevision: HEAD
        path: "argoproj/hitohub/overlays/{{env}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{env}}-hitohub"
