apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-subnet-router
subjects:
  - kind: ServiceAccount
    name: tailscale-subnet-router
    namespace: tailscale
