apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tailscale-state"]
    verbs: ["get", "update", "patch"]
  # create does not support resourceNames; separate rule
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
