apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-es
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: litellm-credentials
    creationPolicy: Owner
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: /lolice/openclaw/ANTHROPIC_API_KEY
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: /lolice/openclaw/LITELLM_MASTER_KEY
