apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-oauth-es
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: google-oauth-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GOOGLE_OAUTH_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /lolice/openclaw/GOOGLE_OAUTH_CLIENT_ID
        metadataPolicy: None
    - secretKey: GOOGLE_OAUTH_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /lolice/openclaw/GOOGLE_OAUTH_CLIENT_SECRET
        metadataPolicy: None
    - secretKey: GOOGLE_OAUTH_REFRESH_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /lolice/openclaw/GOOGLE_OAUTH_REFRESH_TOKEN
        metadataPolicy: None
    - secretKey: GOOGLE_MAPS_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /lolice/openclaw/GOOGLE_MAPS_API_KEY
        metadataPolicy: None
