apiVersion: v1
kind: PersistentVolume
metadata:
  name: palserver-2-saved-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: palserver-2-saved-claim
    volumeAttributes:
      numberOfReplicas: "2"
  claimRef:
    namespace: palserver-2
    name: palserver-2-saved-claim
