apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- application.yaml
patchesStrategicMerge:
- tidb-cluster.yaml
- external-secret-tidb-secret.yaml
- external-secret-hitohub.yaml
- configmap.yaml
- deployment-hitohub-backend.yaml
- service-hitohub-backend.yaml
- deployment-hitohub-frontend.yaml
- service-hitohub-frontend.yaml
- deployment-cloudflared.yaml
