apiVersion: v1
kind: Service
metadata:
  name: hitohub-back-end
spec:
  selector:
    app: hitohub-back-end
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
