apiVersion: v1
kind: Service
metadata:
  name: hitohub-cloudflared-metrics
spec:
  selector:
    app: cloudflared
  type: NodePort
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
      name: tcp
