apiVersion: v1
kind: Service
metadata:
  name: hitohub-frontend
spec:
  selector:
    app: hitohub-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http

