apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidb-cluster
spec:
  version: v7.5.1
  timezone: JST
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: alpine:3.20.3
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 3  # フェイルオーバーを許容するための設定
    replicas: 3  # 高可用性のため、最低3台
    requests:
      storage: "10Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 3  # フェイルオーバーを許容するための設定
    replicas: 3  # 高可用性のため、最低3台
    requests:
      storage: "10Gi"
    config:
      storage:
        reserve-space: "0MB"
      rocksdb:
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 3  # フェイルオーバーを許容するための設定
    replicas: 2  # 負荷分散と冗長性のため、最低2台
    service:
      type: ClusterIP
    config: {}
