apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-self-live-sync
  namespace: argocd
spec:
  destination:
    namespace: obsidian-self-live-sync
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/boxp/lolice
      targetRevision: main
      ref: lolice
    - repoURL: https://apache.github.io/couchdb-helm
      targetRevision: 4.5.6
      chart: couchdb
      helm:
        valueFiles:
          - $lolice/argoproj/obsidian-self-live-sync/values.yaml
        parameters: 
          - name: allowAdminParty
            value: true
          - name: couchdbConfig.couchdb.uuid
            value: 2065a0188aef41ada18cced5b83bdaa4
    - path: argoproj/obsidian-self-live-sync
      repoURL: https://github.com/boxp/lolice
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
