apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-app-secret
  namespace: arc-runners-arch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: arc-github-app-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: github_app_id
      remoteRef:
        key: /lolice/arc/github-app-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: github_app_installation_id
      remoteRef:
        key: /lolice/arc/github-app-installation-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: github_app_private_key
      remoteRef:
        key: /lolice/arc/github-app-private-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
