apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /lolice/n8n/DB_POSTGRESDB_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
