apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-repo-lolice
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: repo-lolice
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:boxp/lolice.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: argocd-image-updater-lolice-github-secret-key
