apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-arc
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: arc
  url: ghcr.io/actions/actions-runner-controller-charts
  type: helm
  enableOCI: "true"
