apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boxp-home
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/boxp/lolice
    targetRevision: HEAD
    path: argoproj/boxp-home
  destination:
    server: https://kubernetes.default.svc
    namespace: boxp-home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 