apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: boxp-home-tunnel-es
  namespace: boxp-home
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
  data:
  - secretKey: tunnel-token
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: boxp-home-tunnel-token
      metadataPolicy: None 