apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secret.yaml
  - cloudflared-deployment.yaml
  - service-cloudflared-metrics.yaml
  - application.yaml 