apiVersion: v1
kind: Service
metadata:
  name: boxp-home-cloudflared-metrics
  namespace: boxp-home
spec:
  selector:
    app: cloudflared
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
      name: metrics 