apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoproj/prometheus-operator
    repoURL: https://github.com/boxp/lolice
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
