apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: observation
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: argoproj/prometheus-operator
      repoURL: https://github.com/boxp/lolice
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
