apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-smtp
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: grafana-smtp
    creationPolicy: Owner
  data:
    - secretKey: GF_SMTP_ENABLED
      remoteRef:
        key: /lolice/grafana/smtp-enabled
    - secretKey: GF_SMTP_HOST
      remoteRef:
        key: /lolice/grafana/smtp-host
    - secretKey: GF_SMTP_USER
      remoteRef:
        key: /lolice/grafana/smtp-user
    - secretKey: GF_SMTP_PASSWORD
      remoteRef:
        key: /lolice/grafana/smtp-password
    - secretKey: GF_SMTP_FROM_ADDRESS
      remoteRef:
        key: /lolice/grafana/smtp-from-address
