apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  namespace: monitoring
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
data:
  contact-points.yaml: |
    apiVersion: 1
    deleteContactPoints:
      - orgId: 1
        uid: de96123xro5c0c
    contactPoints:
      - orgId: 1
        name: boxlab alert
        receivers:
          - uid: de936r1ia7jepd
            type: discord
            settings:
              url: $GRAFANA_DISCORD_WEBHOOK_BOXLAB_ALERT
              use_discord_username: false
            disableResolveMessage: false
  notification-policies.yaml: |
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: boxlab alert
  rules.yaml: |
    apiVersion: 1
    deleteRules:
      - orgId: 1
        uid: fenkaqm8slj40d
      - orgId: 1
        uid: be92yxv4y2mf4b
    groups:
      - orgId: 1
        name: Hito Hub Prod
        folder: ""
        interval: 1m
        rules:
          - uid: ee8z1xs4qz8jkf
            title: hitohub-frontend state running count
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 21600
                  to: 0
                datasourceUid: P1809F7CD0C75ACF3
                model:
                  datasource:
                    type: prometheus
                    uid: P1809F7CD0C75ACF3
                  disableTextWrap: false
                  editorMode: builder
                  expr: kube_deployment_status_replicas_ready{deployment="hitohub-frontend", namespace="prod-hitohub"}
                  fullMetaSearch: false
                  includeNullMetadata: true
                  instant: false
                  interval: ""
                  intervalMs: 15000
                  legendFormat: '{{deployment}}'
                  maxDataPoints: 43200
                  range: true
                  refId: A
                  useBackend: false
              - refId: B
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - B
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: last
                  refId: B
                  type: reduce
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: B
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            dashboardUid: ae8ywexag2rk0d
            panelId: 3
            noDataState: NoData
            execErrState: Error
            for: 1m
            annotations:
              __dashboardUid__: ae8ywexag2rk0d
              __panelId__: "3"
            isPaused: false
            notification_settings:
              receiver: boxlab alert
          - uid: de9c2qjlxwge8e
            title: hitohub-backend state running count
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 21600
                  to: 0
                datasourceUid: P1809F7CD0C75ACF3
                model:
                  datasource:
                    type: prometheus
                    uid: P1809F7CD0C75ACF3
                  disableTextWrap: false
                  editorMode: builder
                  expr: kube_deployment_status_replicas_ready{deployment="hitohub-back-end", namespace="prod-hitohub"}
                  fullMetaSearch: false
                  includeNullMetadata: true
                  instant: false
                  interval: ""
                  intervalMs: 15000
                  legendFormat: '{{deployment}}'
                  maxDataPoints: 43200
                  range: true
                  refId: A
                  useBackend: false
              - refId: B
                relativeTimeRange:
                  from: 21600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - B
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: last
                  refId: B
                  type: reduce
              - refId: C
                relativeTimeRange:
                  from: 21600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: B
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            dashboardUid: ae8ywexag2rk0d
            panelId: 4
            noDataState: NoData
            execErrState: Error
            for: 1m
            annotations:
              __dashboardUid__: ae8ywexag2rk0d
              __panelId__: "4"
            isPaused: false
            notification_settings:
              receiver: boxlab alert
