apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/prometheus-operator/kube-prometheus?ref=release-0.14
- application.yaml
- grafana-lb.yaml
- external-secret.yaml
- cloudflared-deployment.yaml
- alertmanager-pvc.yaml
- grafana-pvc.yaml
- prometheus-pvc.yaml
patchesStrategicMerge:
- overlays/network-policy-grafana.yaml
- overlays/alertmanager.yaml
- overlays/prometheus.yaml
- overlays/grafana.yaml
patchesJson6902:
- target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
      namespace: monitoring
  path: patches/grafana-remove-empty-dir.yaml
