apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/prometheus-operator/kube-prometheus?ref=main
- application.yaml
- grafana-lb.yaml
- external-secret.yaml

# patches:
#   - target:
#       version: v1
#       kind: Service
#       name: grafana
#     patch: |-
#       - op: add
#         path: /spec/type
#         value: LoadBalancer
#       - op: add
#         path: /spec/loadBalancerIP
#         value: 192.168.10.95
#       - op: replace
#         path: /spec/ports/0/targetPort
#         value: 3000
