apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/prometheus-operator/kube-prometheus?ref=v0.18.0
- application.yaml
- grafana-lb.yaml
- external-secret.yaml
- cloudflared-deployment.yaml
- grafana-pvc.yaml
- scrape-config.yaml
- control-plane-node-rules.yaml
- local-llm-gpu-observability-rules.yaml
- cloudflared-pod-monitor.yaml
- etcd-service.yaml
- etcd-servicemonitor.yaml
- pod-monitor-role.yaml
- pod-monitor-role-binding.yaml
- prometheus-servicemonitor-role.yaml
- prometheus-servicemonitor-role-binding.yaml
patchesStrategicMerge:
- overlays/network-policy-grafana.yaml
- overlays/grafana-datasources.yaml
- overlays/network-policy-prometheus-k8s.yaml
- overlays/alertmanager.yaml
- overlays/prometheus.yaml
- overlays/grafana.yaml
- overlays/monitoring-deployment-tolerations.yaml
- overlays/dashboard-placement.yaml
- overlays/grafana-config.yaml
patchesJson6902:
- target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
      namespace: monitoring
  path: patches/grafana-remove-empty-dir.yaml
configMapGenerator:
- name: grafana-dashboard-local-llm-gpu-overview
  namespace: monitoring
  files:
  - local-llm-gpu-overview.json=dashboards/local-llm-gpu-overview.json
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 13.0.2
