apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/prometheus-operator/kube-prometheus?ref=v0.15.0
- application.yaml
- grafana-lb.yaml
- external-secret.yaml
- cloudflared-deployment.yaml
- grafana-pvc.yaml
- scrape-config.yaml
- cloudflared-pod-monitor.yaml
- pod-monitor-role.yaml
- pod-monitor-role-binding.yaml
- prometheus-servicemonitor-role.yaml
- prometheus-servicemonitor-role-binding.yaml
patchesStrategicMerge:
- overlays/network-policy-grafana.yaml
- overlays/network-policy-prometheus-k8s.yaml
- overlays/alertmanager.yaml
- overlays/prometheus.yaml
- overlays/grafana.yaml
- overlays/grafana-config.yaml
patchesJson6902:
- target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
      namespace: monitoring
  path: patches/grafana-remove-empty-dir.yaml
