apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/prometheus-operator/kube-prometheus?ref=main
- application.yaml
- grafana-lb.yaml
- external-secret.yaml
- cloudflared-deployment.yaml
patchesStrategicMerge:
- overlays/network-policy-grafana.yaml