apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: static-config
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: stage-hitohub-cloudflared
      targets:
        -  hitohub-cloudflared-metrics.stage-hitohub.svc.cluster.local:2000
