kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: starrupture-saved-claim
  namespace: starrupture
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
