apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: tailscale-operator-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: /lolice/tailscale/operator-oauth-client-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: /lolice/tailscale/operator-oauth-client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
