apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default-proxy
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
