apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: bastion-network-policy
  namespace: bastion
spec:
  selector: app == 'bastion'
  types:
    - Ingress
    - Egress
  ingress:
    # Only allow traffic from within the same pod (sidecar communication)
    - action: Allow
      protocol: TCP
      source:
        selector: app == 'bastion'
      destination:
        ports:
          - 2222
  egress:
    # Allow DNS to cluster DNS service
    - action: Allow
      protocol: UDP
      destination:
        selector: k8s-app == 'kube-dns'
        namespaceSelector: kubernetes.io/metadata.name == 'kube-system'
        ports:
          - 53
    - action: Allow
      protocol: TCP
      destination:
        selector: k8s-app == 'kube-dns'
        namespaceSelector: kubernetes.io/metadata.name == 'kube-system'
        ports:
          - 53
    # Allow SSH to internal nodes only (192.168.10.0/24)
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 192.168.10.0/24
        ports:
          - 22
    # Allow GitHub access for fetching SSH public keys (initContainer)
    - action: Allow
      protocol: TCP
      destination:
        domains:
          - "github.com"
          - "*.github.com"
        ports:
          - 443
    # Allow Cloudflare connections (HTTPS) for tunnel
    - action: Allow
      protocol: TCP
      destination:
        domains:
          - "*.cloudflare.com"
          - "*.cloudflareaccess.com"
        ports:
          - 443
          - 7844
