apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-hermes-agent-openweathermap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: hermes-agent-openweathermap-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENWEATHERMAP_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: hermes-agent-openweathermap-api-key
        metadataPolicy: None
