apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-hermes-agent-cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: hermes-agent-cloudflared-secret
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: hermes-agent-tunnel-token
        metadataPolicy: None
