apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-snapshot-store
  namespace: etcd-snapshots
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd-snapshot-store
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etcd-snapshot-store
    spec:
      containers:
      - name: snapshot-store
        image: busybox:1.38.0
        command: ["sh", "-c", "sleep infinity"]
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: snapshots
          mountPath: /snapshots
      volumes:
      - name: snapshots
        persistentVolumeClaim:
          claimName: etcd-snapshots
