apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - PersistentVolume
      clusters:
      - "*"
      namespaces:
      - "*-hitohub"
