apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-tidb-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: tidb-secret
    creationPolicy: Owner
  data:
  - secretKey: root
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hitohub-stage-tidb-root-password
      metadataPolicy: None
      
