apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-hitohub
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: hitohub-secret
    creationPolicy: Owner
  data:
  - secretKey: GOOGLE_APPLICATION_CREDENTIALS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hitohub-stage-google-application-credentials
      metadataPolicy: None
  - secretKey: VR_MATCH_FIREBASE_SERVICE_ACCOUNT_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hitohub-stage-firebase-service-account-key
      metadataPolicy: None
  - secretKey: VR_MATCH_MYSQL_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hitohub-stage-tidb-root-password
      metadataPolicy: None
  - secretKey: FIREBASE_API_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hitohub-stage-firebase-api-key
      metadataPolicy: None
  - secretKey: TUNNEL_TOKEN
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None	
      key: hitohub-stage-tunnel-token
      metadataPolicy: None
      