apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      # define a specific role to limit access
      # to certain secrets
      role: arn:aws:iam::839695154978:role/external_secrets_role
      region: ap-northeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: awssm-secret
            key: secret-access-key