apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-registry-helper
  namespace: k8s-ecr-token-updater
spec:
  schedule: "0 */10 * * *"
  successfulJobsHistoryLimit: 2
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-default
          containers:
          - name: ecr-registry-helper
            image: omarxs/awskctl:v1.0
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: aws-credentials
              - configMapRef:
                  name: ecr-registry-helper-cm
            command:
              - /bin/bash
              - -c
              - |-
                ECR_TOKEN="$(aws ecr get-login-password --region ${AWS_REGION})"
                # システム用の除外namespaceリスト（必要に応じて調整）
                EXCLUDE_NAMESPACES="kube-public kube-node-lease default"
                
                echo "Starting ECR credential update for all namespaces..."
                for NAMESPACE_NAME in $(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}')
                do
                  # 除外リストにあるnamespaceはスキップ
                  if echo "$EXCLUDE_NAMESPACES" | grep -qw "$NAMESPACE_NAME"; then
                    echo "Skipping system namespace: $NAMESPACE_NAME"
                    continue
                  fi
                  
                  echo "Updating ECR credentials for namespace: $NAMESPACE_NAME"
                  kubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME -n $NAMESPACE_NAME
                  kubectl create secret docker-registry $DOCKER_SECRET_NAME --docker-server=https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com --docker-username=AWS --docker-password=${ECR_TOKEN} --namespace=$NAMESPACE_NAME
                done
                echo "Secret was successfully updated for all namespaces at $(date)"
          restartPolicy: Never
