apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-registry-helper
  namespace: k8s-ecr-token-updater
spec:
  schedule: "0 */10 * * *"
  successfulJobsHistoryLimit: 2
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-default
          containers:
          - name: ecr-registry-helper
            image: omarxs/awskctl:v1.0
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: aws-credentials
              - configMapRef:
                  name: ecr-registry-helper-cm
            command:
              - /bin/bash
              - -c
              - |-
                echo "Starting ECR credential update for all namespaces..."
                ECR_TOKEN="$(aws ecr get-login-password --region ${AWS_REGION})"
                
                # 除外するnamespaceのリスト
                EXCLUDED_NAMESPACES="default tigera-operator tidb-admin reloader observation monitoring longhorn-system kube-system kube-public kube-node-lease k8s-ecr-token-updater k8s-dashboard external-secrets calico-system calico-apiserver"
                
                # すべてのnamespaceを取得
                NAMESPACES=$(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}')
                
                for NAMESPACE_NAME in $NAMESPACES
                do
                  # 除外リストにnamespaceが含まれているかチェック
                  if [[ $EXCLUDED_NAMESPACES =~ (^|[[:space:]])$NAMESPACE_NAME($|[[:space:]]) ]]; then
                    echo "Skipping excluded namespace: $NAMESPACE_NAME"
                    continue
                  fi
                  
                  echo "Updating ECR credentials for namespace: $NAMESPACE_NAME"
                  kubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME -n $NAMESPACE_NAME
                  kubectl create secret docker-registry $DOCKER_SECRET_NAME --docker-server=https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com --docker-username=AWS --docker-password=${ECR_TOKEN} --namespace=$NAMESPACE_NAME
                done
                
                echo "Secret was successfully updated for all namespaces at $(date)"
          restartPolicy: Never
