apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: aws-credentials
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: k8s-ecr-token-updater-aws-access-key
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: k8s-ecr-token-updater-aws-secret
  - secretKey: AWS_ACCOUNT_ID
    remoteRef:
      key: k8s-ecr-token-updater-aws-account-id
