apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: k8s-ecr-token-updater
  name: role-full-access-to-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["regcred"] # Replace with your desired ECR token secret name
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-role-binding
  namespace: k8s-ecr-token-updater
subjects:
- kind: ServiceAccount
  name: sa-default # Replace with your service account name if different
  namespace: k8s-ecr-token-updater
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets # Replace with your role name if different 
  apiGroup: ""