apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  destination:
    namespace: tigera-operator
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/boxp/lolice
      targetRevision: main
      ref: lolice
    - repoURL: https://projectcalico.docs.tigera.io/charts
      targetRevision: 3.29.1
      chart: tigera-operator
      helm:
        valueFiles:
          - $lolice/argoproj/calico/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
