apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  destination:
    namespace: tigera-operator
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/boxp/lolice
      targetRevision: main
      ref: lolice
    - repoURL: https://projectcalico.docs.tigera.io/charts
      targetRevision: 3.30.2
      chart: tigera-operator
      helm:
        valueFiles:
          - $lolice/argoproj/calico/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
      managedFieldsManagers:
        - argocd-controller
