apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-llm
  namespace: argocd
spec:
  destination:
    namespace: local-llm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoproj/local-llm
    repoURL: https://github.com/boxp/lolice
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
