apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-llm

resources:
  - namespace.yaml
  - models-config.yaml
  - envoy-config.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
