apiVersion: v1
kind: Service
metadata:
  name: llama-server-lan
  labels:
    app.kubernetes.io/name: llama-server
    app.kubernetes.io/component: lan-load-balancer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.95
  selector:
    app: llama-server
  ports:
    - name: http
      port: 8080
      targetPort: http
