apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llama-server-envoy
  labels:
    app: llama-server
spec:
  selector:
    matchLabels:
      app: llama-server
  namespaceSelector:
    matchNames:
      - local-llm
  endpoints:
    - port: metrics
      interval: 30s
      path: /stats/prometheus
