apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: tunnel-token
    remoteRef:
      key: longhorn-tunnel-token
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: /longhorn/backup/aws-access-key-id
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: /longhorn/backup/aws-secret-access-key
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
