on:
  push:
    branches:
      - '**'  # すべてのブランチが対象

permissions:
  id-token: write  # GitHub OIDCトークンを取得するための権限
  contents: read   # リポジトリのコンテンツ読み取り権限

jobs:
  get-pods:
    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_TUNNEL_URL: "https://k8s.b0xp.io"  # Kubernetes APIのURL
      K8S_NAMESPACE: "argocd"  # KubernetesのNamespace

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate and obtain OIDC token
        id: auth
        run: |
          echo "Authenticating with GitHub OIDC to obtain ID token..."
          
          # GitHub OIDCトークンの取得
          OIDC_TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN" \
                        "https://token.actions.githubusercontent.com/.well-known/openid-configuration")

          echo "OIDC Token Configuration:"
          echo $OIDC_TOKEN | jq

          # ここで実際にIDトークンを取得
          ID_TOKEN=$(curl -s -X POST "https://token.actions.githubusercontent.com/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "client_id=sigstore" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "audience=cloudflare" \
            | jq -r '.id_token')

          if [ -z "$ID_TOKEN" ]; then
            echo "ERROR: Failed to retrieve OIDC token."
            exit 1
          fi

          echo "ID_TOKEN=$ID_TOKEN" >> $GITHUB_ENV  # ID_TOKENをエクスポート

      - name: Get Kubernetes Pods from API
        run: |
          echo "Fetching pods from Kubernetes API at $CLOUDFLARE_TUNNEL_URL..."
          
          # Kubernetes APIのGETリクエスト
          API_URL="$CLOUDFLARE_TUNNEL_URL/api/v1/namespaces/$K8S_NAMESPACE/pods"
          
          RESPONSE=$(curl -s -X GET $API_URL \
            -H "Authorization: Bearer $ID_TOKEN" \
            -H "Accept: application/json")
          
          echo "Response from API:"
          echo $RESPONSE | jq
