name: Validate Kubernetes Manifests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if manifests directory exists
        id: check_manifests
        run: |
          if [ -d "argoproj" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install kubeval
        if: steps.check_manifests.outputs.exists == 'true'
        run: |
          echo "Installing kubeval using apt-get"
          sudo apt-get update
          sudo apt-get install -y kubectl
          sudo apt-get install -y kubeval

      - name: Validate Kubernetes manifests
        if: steps.check_manifests.outputs.exists == 'true'
        run: |
          files=$(find argoproj -type f \( -name "*.yaml" -o -name "*.yml" \))
          if [ -z "$files" ]; then
            echo "No YAML files found in manifests"
            exit 0
          fi
          echo "Found files: $files"
          for file in $files; do
            echo "Validating $file"
            kubeval -v "$file"
          done

      - name: Warn if manifests directory does not exist
        if: steps.check_manifests.outputs.exists == 'false'
        run: echo "argoproj directory not found, skipping Kubernetes manifest validation."
