apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openhands
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-image=839695154978.dkr.ecr.ap-northeast-1.amazonaws.com/openhands-runtime
    argocd-image-updater.argoproj.io/my-image.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/boxp/lolice
    targetRevision: main
    path: argoproj/openhands
  destination:
    server: https://kubernetes.default.svc
    namespace: openhands
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
    automated:
      prune: true
      selfHeal: true
