apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands
  namespace: openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
    spec:
      containers:
      - name: openhands
        image: docker.all-hands.dev/all-hands-ai/openhands:0.27
        ports:
        - containerPort: 3000
        env:
        - name: SANDBOX_RUNTIME_CONTAINER_IMAGE
          value: docker.all-hands.dev/all-hands-ai/runtime:0.27-nikolaik
        - name: WORKSPACE_MOUNT_PATH
          value: /opt/workspace_base
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: openhands-state
          mountPath: /.openhands-state
        - name: workspace
          mountPath: /opt/workspace_base
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: openhands-state
        persistentVolumeClaim:
          claimName: openhands-state-pvc
      - name: workspace
        persistentVolumeClaim:
          claimName: openhands-data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - golyat-1 