apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands
  namespace: openhands
spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
    spec:
      hostNetwork: true
      containers:
      - name: openhands
        image: docker.all-hands.dev/all-hands-ai/openhands:0.26
        ports:
        - containerPort: 3000
        env:
        - name: SANDBOX_RUNTIME_CONTAINER_IMAGE
          value: docker.all-hands.dev/all-hands-ai/runtime:0.27-nikolaik
        - name: SANDBOX_LOCAL_RUNTIME_URL
          value: http://127.0.0.1
        # 注意: このIPアドレスは実際のgolyat-1ノードのIPアドレスに置き換えてください
        # 以下のコマンドで取得できます:
        # kubectl get nodes golyat-1 -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}'
        - name: WORKSPACE_MOUNT_PATH
          value: /opt/workspace_base
        # AWS Parameter Reader関連の環境変数
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: parameter-reader-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: parameter-reader-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "asia-northeast-1"
        - name: AWS_DEFAULT_REGION
          value: "asia-northeast-1"
        - name: BEDROCK_MODEL_ID
          value: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: openhands-state
          mountPath: /.openhands-state
        - name: workspace
          mountPath: /opt/workspace_base
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: openhands-state
        persistentVolumeClaim:
          claimName: openhands-state-pvc
      - name: workspace
        persistentVolumeClaim:
          claimName: openhands-data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - golyat-1 

