apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands
  namespace: openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
    spec:
      initContainers:
      - name: setup-host-docker-internal
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          # ConfigMapからノードIPを取得して/etc/hosts.nodeに書き込む
          echo "Setting up host.docker.internal to point to node IP: ${NODE_IP}"
          echo "${NODE_IP} host.docker.internal" > /etc/hosts.node
        env:
        - name: NODE_IP
          valueFrom:
            configMapKeyRef:
              name: node-ip-config
              key: golyat-1-ip
        volumeMounts:
        - name: hosts-file
          mountPath: /etc/hosts.node
      containers:
      - name: openhands
        image: docker.all-hands.dev/all-hands-ai/openhands:0.27
        ports:
        - containerPort: 3000
        env:
        - name: SANDBOX_RUNTIME_CONTAINER_IMAGE
          value: docker.all-hands.dev/all-hands-ai/runtime:0.27-nikolaik
        - name: WORKSPACE_MOUNT_PATH
          value: /opt/workspace_base
        - name: HOST_DOCKER_INTERNAL
          valueFrom:
            configMapKeyRef:
              name: node-ip-config
              key: golyat-1-ip
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: openhands-state
          mountPath: /.openhands-state
        - name: workspace
          mountPath: /opt/workspace_base
        - name: hosts-file
          mountPath: /etc/hosts.openhands
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        # コンテナ起動時にホストファイルをコピー
        command:
        - /bin/sh
        - -c
        - |
          # ホストファイルを/etc/hostsにコピー
          if [ -f /etc/hosts.openhands ]; then
            cat /etc/hosts.openhands >> /etc/hosts
          fi
          # OpenHandsの通常の起動コマンドを実行
          exec /usr/local/bin/docker-entrypoint.sh
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: openhands-state
        persistentVolumeClaim:
          claimName: openhands-state-pvc
      - name: workspace
        persistentVolumeClaim:
          claimName: openhands-data
      - name: hosts-file
        emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - golyat-1 