apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-cleanup
  namespace: openhands
spec:
  schedule: "0 0 * * *"  # 毎日午前0時に実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-cleanup
            image: docker:cli
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting Docker cleanup for OpenHands DinD container"
              # DinDコンテナ内部の未使用Dockerリソースを削除
              # OpenHandsポッドの名前を動的に取得
              OPENHANDS_POD=$(kubectl get pods -n openhands -l app=openhands -o jsonpath='{.items[0].metadata.name}')
              if [ -n "$OPENHANDS_POD" ]; then
                echo "Found OpenHands pod: $OPENHANDS_POD"
                kubectl exec -n openhands $OPENHANDS_POD -c dind-daemon -- docker system prune -af --volumes
                echo "Docker cleanup completed for pod $OPENHANDS_POD"
              else
                echo "No OpenHands pod found"
              fi
          serviceAccountName: docker-cleanup-sa  # 追加：クリーンアップ用のサービスアカウント
          restartPolicy: OnFailure 