apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: openhands
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
  data:
  - secretKey: tunnel-token
    remoteRef:
      conversionStrategy: Default       
      decodingStrategy: None    
      key: openhands-tunnel-token
      metadataPolicy: None 
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: parameter-reader-credentials
  namespace: openhands
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: parameter-reader-credentials
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: parameter-reader-access-key-id
      metadataPolicy: None
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: parameter-reader-secret-access-key
      metadataPolicy: None 