apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: openhands
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
  data:
  - secretKey: tunnel-token
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None	
      key: openhands-tunnel-token
      metadataPolicy: None 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bedrock-credentials
  namespace: openhands
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: bedrock-credentials
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: bedrock-access-key-id
      metadataPolicy: None
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: bedrock-secret-access-key
      metadataPolicy: None 