apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mcp-server
  namespace: openhands
  labels:
    app: k8s-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mcp-server
  template:
    metadata:
      labels:
        app: k8s-mcp-server
    spec:
      serviceAccountName: k8s-mcp-server-sa
      containers:
      - name: k8s-mcp-server
        image: flux159/mcp-server-kubernetes # Use the specified public image
        imagePullPolicy: IfNotPresent # Or Always, depending on update needs
        ports:
        - containerPort: 3001
          name: http-sse
        env:
        - name: ENABLE_UNSAFE_SSE_TRANSPORT
          value: "1"
        - name: PORT
          value: "3001"
        - name: DEBUG
          value: "*"
        # Add readiness and liveness probes for better reliability
        readinessProbe:
          tcpSocket:
            port: http-sse
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: http-sse
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
