apiVersion: v1
kind: Service
metadata:
  name: k8s-mcp-server-service
  namespace: openhands
  labels:
    app: k8s-mcp-server
spec:
  selector:
    app: k8s-mcp-server
  ports:
  - name: http-sse
    protocol: TCP
    port: 3001 
    targetPort: http-sse # Refers to the containerPort name in the Deployment
  type: ClusterIP
