---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhands-state-pvc
  namespace: openhands
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhands-data
  namespace: openhands
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi 